vich_uploader:
    db_driver: orm

    mappings:
        objekts:
            uri_prefix: /images/objekts
            upload_destination: '%kernel.project_dir%/public/images/objekts'
       #     namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
